# v1.57.1
issues:
  new-from-rev: 9101977dc81f64db077b9a1eda2fe401359854c9
  # Maximum issues count per one linter. Set to 0 to disable.
  # Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable.
  # Default is 3.
  max-same-issues: 0
  include:
    - EXC0012
    - EXC0014
  exclude-rules:
    # Exclude duplicate code and function length and complexity checking in test
    # files (due to common repeats and long functions in test code)
    - path: _(test|gen)\.go
      linters:
        - cyclop
        - dupl
        - gocognit
        - funlen
        - lll
    - path: _types\.go
      linters:
        - lll
    - path: fwprovider/tests/.*\.go
      linters:
        - paralleltest
    # Exclude `lll` issues for long lines with URLs.
    - linters:
        - lll
      source: "^.*https?://.*$"
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  cyclop:
    max-complexity: 25
  dupl:
    threshold: 150
  goconst:
    min-len: 10
    min-occurrences: 4
  funlen:
    lines: 80
    statements: 60
  errcheck:
    check-blank: true
linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - gocyclo
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - rowserrcheck
    - scopelint
    - structcheck
    - varcheck
    - wastedassign
    # require massive refactoring
    - cyclop
    - forcetypeassert
    - funlen
    - gocognit
    # others
    - depguard
    - exhaustivestruct
    - exhaustruct
    - gci
    - goerr113
    - gomnd
    - ireturn
    - maintidx
    - nestif
    - nlreturn
    - perfsprint
    - tagliatelle
    - testpackage
    - tparallel
    - varnamelen
  fast: false
