pull_request_rules:
  - name: Automatic approval of bpg`s pull requests
    conditions:
      - author=bpg
      - "#approved-reviews-by=0"
    actions:
      review:
        type: APPROVE
        message: ":robot: LGTM! *beep* *boop*"
