pull_request_rules:
  - name: Automatic approval of bpg`s pull requests
    conditions:
      - author=bpg
      - label=autoapprove
      - "#approved-reviews-by=0"
    actions:
      review:
        type: APPROVE
        message: ":robot: LGTM! *beep* *boop*"
  - name: Automatic approval of renovate's pull requests
    conditions:
      - author=renovate[bot]
      - label=renovate/github-action
      - "#approved-reviews-by=0"
    actions:
      review:
        type: APPROVE
  - name: Automatic approval of all-contributors's pull requests
    conditions:
      - author=allcontributors[bot]
      - "#approved-reviews-by=0"
    actions:
      review:
        type: APPROVE
      merge:
        method: squash
