/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package options

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/bpg/terraform-provider-proxmox/fwprovider/attribute"
	"github.com/bpg/terraform-provider-proxmox/fwprovider/config"
	"github.com/bpg/terraform-provider-proxmox/fwprovider/migration"
	customtypes "github.com/bpg/terraform-provider-proxmox/fwprovider/types"
	"github.com/bpg/terraform-provider-proxmox/fwprovider/validators"
	"github.com/bpg/terraform-provider-proxmox/proxmox"
	"github.com/bpg/terraform-provider-proxmox/proxmox/cluster"
)

var (
	_ resource.Resource                = &clusterOptionsResource{}
	_ resource.ResourceWithConfigure   = &clusterOptionsResource{}
	_ resource.ResourceWithImportState = &clusterOptionsResource{}
)

// NewClusterOptionsResource manages cluster options resource.
func NewClusterOptionsResource() resource.Resource {
	return &clusterOptionsResource{}
}

type clusterOptionsResource struct {
	client proxmox.Client
}

func (r *clusterOptionsResource) Metadata(
	_ context.Context,
	req resource.MetadataRequest,
	resp *resource.MetadataResponse,
) {
	resp.TypeName = req.ProviderTypeName + "_cluster_options"
}

// Schema defines the schema for the resource.
func (r *clusterOptionsResource) Schema(
	_ context.Context,
	_ resource.SchemaRequest,
	resp *resource.SchemaResponse,
) {
	resp.Schema = schema.Schema{
		DeprecationMessage: migration.DeprecationMessage("proxmox_cluster_options"),
		Description:        "Manages Proxmox VE Cluster Datacenter options.",
		Attributes: map[string]schema.Attribute{
			"id": attribute.ResourceID(),
			"email_from": schema.StringAttribute{
				Description: "email address to send notification from (default is root@$hostname).",
				Optional:    true,
			},
			"keyboard": schema.StringAttribute{
				Description: "Default keyboard layout for vnc server.",
				MarkdownDescription: "Default keyboard layout for vnc server. Must be `de` | " +
					"`de-ch` | `da` | `en-gb` | `en-us` | `es` | `fi` | `fr` | `fr-be` | `fr-ca` " +
					"| `fr-ch` | `hu` | `is` | `it` | `ja` | `lt` | `mk` | `nl` | `no` | `pl` | " +
					"`pt` | `pt-br` | `sv` | `sl` | `tr`.",
				Optional: true,
				Validators: []validator.String{
					validators.KeyboardLayoutValidator(),
				},
			},
			"max_workers": schema.Int64Attribute{
				Description: "Defines how many workers (per node) are maximal started on" +
					" actions like 'stopall VMs' or task from the ha-manager.",
				Optional: true,
			},
			"language": schema.StringAttribute{
				Description: "Default GUI language.",
				MarkdownDescription: "Default GUI language. Must be `ca` | `da` | `de` " +
					"| `en` | `es` | `eu` | `fa` | `fr` | `he` | `it` | `ja` | `nb` | " +
					"`nn` | `pl` | `pt_BR` | `ru` | `sl` | `sv` | `tr` | `zh_CN` | `zh_TW`.",
				Optional: true,
				Validators: []validator.String{
					validators.LanguageValidator(),
				},
			},
			"console": schema.StringAttribute{
				Description: "Select the default Console viewer.",
				MarkdownDescription: "Select the default Console viewer. " +
					"Must be `applet` | `vv`| `html5` | `xtermjs`. " +
					"You can either use the builtin java applet (VNC; deprecated and maps to html5), " +
					"an external virt-viewer compatible application (SPICE), " +
					"an HTML5 based vnc viewer (noVNC), " +
					"or an HTML5 based console client (xtermjs). " +
					"If the selected viewer is not available " +
					"(e.g. SPICE not activated for the VM), " +
					"the fallback is noVNC.",
				Optional: true,
				Validators: []validator.String{stringvalidator.OneOf([]string{
					"applet",
					"vv",
					"html5",
					"xtermjs",
				}...)},
			},
			"http_proxy": schema.StringAttribute{
				Description: "Specify external http proxy which is used for downloads.",
				MarkdownDescription: "Specify external http proxy which is used for downloads " +
					"(example: `http://username:password@host:port/`).",
				Optional: true,
			},
			"mac_prefix": schema.StringAttribute{
				Description: "Prefix for autogenerated MAC addresses.",
				Optional:    true,
				Computed:    true,
			},
			"description": schema.StringAttribute{
				Description: "Datacenter description. Shown in the web-interface datacenter notes panel. " +
					"This is saved as comment inside the configuration file.",
				Optional: true,
			},
			"ha_shutdown_policy": schema.StringAttribute{
				Description: "Cluster wide HA shutdown policy.",
				MarkdownDescription: "Cluster wide HA shutdown policy. " +
					"Must be `freeze` | `failover` | `migrate` | `conditional` (default is `conditional`).",
				Optional: true,
				Validators: []validator.String{stringvalidator.OneOf([]string{
					"freeze",
					"failover",
					"migrate",
					"conditional",
				}...)},
			},
			"migration_type": schema.StringAttribute{
				Description: "Cluster wide migration type.",
				MarkdownDescription: "Cluster wide migration type. Must be `secure` | `insecure` " +
					"(default is `secure`).",
				Optional: true,
				Validators: []validator.String{stringvalidator.OneOf([]string{
					"secure",
					"insecure",
				}...)},
			},
			"migration_cidr": schema.StringAttribute{
				Description: "Cluster wide migration network CIDR.",
				Optional:    true,
				CustomType:  customtypes.IPCIDRType{},
			},
			"next_id": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"lower": schema.Int64Attribute{
						Description: "The minimum number for the next free VM ID.",
						MarkdownDescription: "The minimum number for the next free VM ID. " +
							fmt.Sprintf("Must be higher or equal to %d", ClusterOptionsNextIDLowerMinimum),
						Optional: true,
						Validators: []validator.Int64{
							int64validator.AtLeast(ClusterOptionsNextIDLowerMinimum),
						},
					},
					"upper": schema.Int64Attribute{
						Description: "The maximum number for the next free VM ID.",
						MarkdownDescription: "The maximum number for the next free VM ID. " +
							fmt.Sprintf("Must be less or equal to %d", ClusterOptionsNextIDLowerMaximum),
						Optional: true,
						Validators: []validator.Int64{
							int64validator.AtMost(ClusterOptionsNextIDLowerMaximum),
						},
					},
				},
				Description: "The ranges for the next free VM ID auto-selection pool.",
				Optional:    true,
			},
			"notify": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"ha_fencing_mode": schema.StringAttribute{
						Description:         "Cluster-wide notification settings for the HA fencing mode.",
						MarkdownDescription: "Cluster-wide notification settings for the HA fencing mode. Must be `always` | `never`.",
						Optional:            true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								[]string{
									"always",
									"never",
								}...,
							),
						},
					},
					"ha_fencing_target": schema.StringAttribute{
						Description:         "Cluster-wide notification settings for the HA fencing target.",
						MarkdownDescription: "Cluster-wide notification settings for the HA fencing target.",
						Optional:            true,
						Validators: []validator.String{
							stringvalidator.UTF8LengthAtLeast(1),
							stringvalidator.RegexMatches(regexp.MustCompile(`^\S|^$`), "must not start with whitespace"),
							stringvalidator.RegexMatches(regexp.MustCompile(`\S$|^$`), "must not end with whitespace"),
						},
					},
					"package_updates": schema.StringAttribute{
						Description: "Cluster-wide notification settings for package updates.",
						MarkdownDescription: "Cluster-wide notification settings for package updates. " +
							"Must be `auto` | `always` | `never`. ",
						Optional: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								[]string{
									"auto",
									"always",
									"never",
								}...,
							),
						},
					},
					"package_updates_target": schema.StringAttribute{
						Description:         "Cluster-wide notification settings for the package updates target.",
						MarkdownDescription: "Cluster-wide notification settings for the package updates target.",
						Optional:            true,
						Validators: []validator.String{
							stringvalidator.UTF8LengthAtLeast(1),
							stringvalidator.RegexMatches(regexp.MustCompile(`^\S|^$`), "must not start with whitespace"),
							stringvalidator.RegexMatches(regexp.MustCompile(`\S$|^$`), "must not end with whitespace"),
						},
					},
					"replication": schema.StringAttribute{
						Description: "Cluster-wide notification settings for replication.",
						MarkdownDescription: "Cluster-wide notification settings for replication. " +
							"Must be `always` | `never`. ",
						Optional: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								[]string{
									"always",
									"never",
								}...,
							),
						},
					},
					"replication_target": schema.StringAttribute{
						Description:         "Cluster-wide notification settings for the replication target.",
						MarkdownDescription: "Cluster-wide notification settings for the replication target.",
						Optional:            true,
						Validators: []validator.String{
							stringvalidator.UTF8LengthAtLeast(1),
							stringvalidator.RegexMatches(regexp.MustCompile(`^\S|^$`), "must not start with whitespace"),
							stringvalidator.RegexMatches(regexp.MustCompile(`\S$|^$`), "must not end with whitespace"),
						},
					},
				},
				Description: "Cluster-wide notification settings.",
				Optional:    true,
			},
			"crs_ha": schema.StringAttribute{
				Description:         "Cluster resource scheduling setting for HA.",
				MarkdownDescription: "Cluster resource scheduling setting for HA. Must be `static` | `basic` (default is `basic`).",
				Optional:            true,
				Computed:            true,
				Validators: []validator.String{stringvalidator.OneOf([]string{
					"static",
					"basic",
				}...)},
			},
			"crs_ha_rebalance_on_start": schema.BoolAttribute{
				Description: "Cluster resource scheduling setting for HA rebalance on start.",
				Optional:    true,
			},
			"bandwidth_limit_clone": schema.Int64Attribute{
				Description: "Clone I/O bandwidth limit in KiB/s.",
				Optional:    true,
			},
			"bandwidth_limit_default": schema.Int64Attribute{
				Description: "Default I/O bandwidth limit in KiB/s.",
				Optional:    true,
			},
			"bandwidth_limit_migration": schema.Int64Attribute{
				Description: "Migration I/O bandwidth limit in KiB/s.",
				Optional:    true,
			},
			"bandwidth_limit_move": schema.Int64Attribute{
				Description: "Move I/O bandwidth limit in KiB/s.",
				Optional:    true,
			},
			"bandwidth_limit_restore": schema.Int64Attribute{
				Description: "Restore I/O bandwidth limit in KiB/s.",
				Optional:    true,
			},
		},
	}
}

func (r *clusterOptionsResource) Configure(
	_ context.Context,
	req resource.ConfigureRequest,
	resp *resource.ConfigureResponse,
) {
	if req.ProviderData == nil {
		return
	}

	cfg, ok := req.ProviderData.(config.Resource)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *proxmox.Client, got: %T", req.ProviderData),
		)

		return
	}

	r.client = cfg.Client
}

// Create update must-existing cluster options.
func (r *clusterOptionsResource) Create(
	ctx context.Context,
	req resource.CreateRequest,
	resp *resource.CreateResponse,
) {
	var plan clusterOptionsModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Cluster().CreateUpdateOptions(ctx, plan.toAPI())
	if err != nil {
		resp.Diagnostics.AddError("Unable to Create Cluster Options", err.Error())

		return
	}

	plan.ID = types.StringValue("cluster")

	r.read(ctx, &plan, &resp.Diagnostics)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *clusterOptionsResource) read(ctx context.Context, model *clusterOptionsModel, diags *diag.Diagnostics) {
	options, err := r.client.Cluster().GetOptions(ctx)
	if err != nil {
		diags.AddError("Unable to Read Cluster Options", err.Error())

		return
	}

	if err := model.fromAPI(options); err != nil {
		diags.AddError("Unable to Read Cluster Options", err.Error())

		return
	}
}

// Read reads cluster options.
func (r *clusterOptionsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state clusterOptionsModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	r.read(ctx, &state, &resp.Diagnostics)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Update updates cluster options.
func (r *clusterOptionsResource) Update(
	ctx context.Context,
	req resource.UpdateRequest,
	resp *resource.UpdateResponse,
) {
	var plan, state clusterOptionsModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	body := plan.toAPI()

	var toDelete []string

	attribute.CheckDelete(plan.Keyboard, state.Keyboard, &toDelete, "keyboard")

	// Composite fields use checkCompositeDelete instead of attribute.CheckDelete because
	// multiple model fields are serialized into a single API parameter string (e.g. "type=secure,network=10.0.0.0/8").
	// attribute.CheckDelete expects attr.Value types, not serialized strings.
	checkCompositeDelete(plan.bandwidthData(), state.bandwidthData(), &toDelete, "bwlimit")
	checkCompositeDelete(plan.crsData(), state.crsData(), &toDelete, "crs")
	checkCompositeDelete(plan.haData(), state.haData(), &toDelete, "ha")
	checkCompositeDelete(plan.migrationData(), state.migrationData(), &toDelete, "migration")
	checkCompositeDelete(plan.nextIDData(), state.nextIDData(), &toDelete, "next-id")
	checkCompositeDelete(plan.notifyData(), state.notifyData(), &toDelete, "notify")

	attribute.CheckDelete(plan.EmailFrom, state.EmailFrom, &toDelete, "email_from")
	attribute.CheckDelete(plan.Language, state.Language, &toDelete, "language")
	attribute.CheckDelete(plan.Console, state.Console, &toDelete, "console")
	attribute.CheckDelete(plan.HTTPProxy, state.HTTPProxy, &toDelete, "http_proxy")
	attribute.CheckDelete(plan.MacPrefix, state.MacPrefix, &toDelete, "mac_prefix")
	attribute.CheckDelete(plan.Description, state.Description, &toDelete, "description")
	attribute.CheckDelete(plan.MaxWorkers, state.MaxWorkers, &toDelete, "max_workers")

	if len(toDelete) > 0 {
		body.Delete = toDelete
	}

	err := r.client.Cluster().CreateUpdateOptions(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Unable to Update Cluster Options", err.Error())

		return
	}

	r.read(ctx, &plan, &resp.Diagnostics)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

// Delete deletes cluster options.
func (r *clusterOptionsResource) Delete(
	ctx context.Context,
	req resource.DeleteRequest,
	resp *resource.DeleteResponse,
) {
	var state clusterOptionsModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	// Delete() has no plan — we simply clear all fields that have values in state.
	// attribute.CheckDelete cannot be used here because it compares plan vs state.
	var toDelete []string

	if attribute.IsDefined(state.Keyboard) {
		toDelete = append(toDelete, "keyboard")
	}

	if state.bandwidthData() != "" {
		toDelete = append(toDelete, "bwlimit")
	}

	if state.crsData() != "" {
		toDelete = append(toDelete, "crs")
	}

	if state.haData() != "" {
		toDelete = append(toDelete, "ha")
	}

	if state.migrationData() != "" {
		toDelete = append(toDelete, "migration")
	}

	if state.nextIDData() != "" {
		toDelete = append(toDelete, "next-id")
	}

	if state.notifyData() != "" {
		toDelete = append(toDelete, "notify")
	}

	if attribute.IsDefined(state.EmailFrom) {
		toDelete = append(toDelete, "email_from")
	}

	if attribute.IsDefined(state.Language) {
		toDelete = append(toDelete, "language")
	}

	if attribute.IsDefined(state.Console) {
		toDelete = append(toDelete, "console")
	}

	if attribute.IsDefined(state.HTTPProxy) {
		toDelete = append(toDelete, "http_proxy")
	}

	if attribute.IsDefined(state.MacPrefix) {
		toDelete = append(toDelete, "mac_prefix")
	}

	if attribute.IsDefined(state.Description) {
		toDelete = append(toDelete, "description")
	}

	if attribute.IsDefined(state.MaxWorkers) {
		toDelete = append(toDelete, "max_workers")
	}

	if len(toDelete) > 0 {
		body := &cluster.OptionsRequestData{
			Delete: toDelete,
		}

		err := r.client.Cluster().CreateUpdateOptions(ctx, body)
		if err != nil {
			resp.Diagnostics.AddError("Unable to Delete Cluster Options", err.Error())
		}
	}
}

// ImportState imports cluster options.
func (r *clusterOptionsResource) ImportState(
	ctx context.Context,
	req resource.ImportStateRequest,
	resp *resource.ImportStateResponse,
) {
	state := clusterOptionsModel{ID: types.StringValue(req.ID)}
	r.read(ctx, &state, &resp.Diagnostics)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Short-name alias for the cluster options resource (ADR-007).

var (
	_ resource.Resource                = &clusterOptionsResourceShort{}
	_ resource.ResourceWithConfigure   = &clusterOptionsResourceShort{}
	_ resource.ResourceWithImportState = &clusterOptionsResourceShort{}
	_ resource.ResourceWithMoveState   = &clusterOptionsResourceShort{}
)

type clusterOptionsResourceShort struct {
	clusterOptionsResource
}

// NewClusterOptionsShortResource creates a short-name alias for the cluster options resource.
func NewClusterOptionsShortResource() resource.Resource {
	return &clusterOptionsResourceShort{}
}

func (r *clusterOptionsResourceShort) Metadata(
	_ context.Context,
	_ resource.MetadataRequest,
	resp *resource.MetadataResponse,
) {
	resp.TypeName = "proxmox_cluster_options"
}

func (r *clusterOptionsResourceShort) Schema(
	ctx context.Context,
	req resource.SchemaRequest,
	resp *resource.SchemaResponse,
) {
	r.clusterOptionsResource.Schema(ctx, req, resp)
	resp.Schema.DeprecationMessage = ""
}

func (r *clusterOptionsResourceShort) MoveState(ctx context.Context) []resource.StateMover {
	schemaResp := &resource.SchemaResponse{}
	r.Schema(ctx, resource.SchemaRequest{}, schemaResp)

	return []resource.StateMover{
		migration.PrefixMoveState(
			"proxmox_virtual_environment_cluster_options",
			&schemaResp.Schema,
		),
	}
}
