name: Semgrep

on:
  pull_request: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: 29 16 * * *

jobs:
  semgrep:
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: "${{ secrets.SEMGREP_APP_TOKEN }}"
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semgrep
        run: semgrep ci
