name: Tests

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 1

      - name: Filter paths
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'

      - name: Setup Go
        if: ${{ steps.filter.outputs.go == 'true' }}
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "**/*.sum"

      - name: Get dependencies
        if: ${{ steps.filter.outputs.go == 'true' }}
        run: go mod download

      - name: Build
        if: ${{ steps.filter.outputs.go == 'true' }}
        run: go vet . && go build -v .

  test:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 1

      - name: Filter paths
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "**/*.sum"

      - name: Get dependencies
        if: ${{ steps.filter.outputs.go == 'true' }}
        run: go mod download

      - name: Set up gotestfmt
        run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Unit tests
        if: ${{ steps.filter.outputs.go == 'true' }}
        timeout-minutes: 10
        run: go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt -hide empty-packages

      - name: Upload test log
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ steps.filter.outputs.go == 'true' }}
        with:
          name: test-log
          path: /tmp/gotest.log

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4

      - name: Check for uncommitted changes in generated docs
        run: make docs && git diff --exit-code
